<?php

namespace App\Http\Resources\Product;

use Illuminate\Http\Resources\Json\ResourceCollection;

/* Aaron
    NOTE:   This file is generated by executing the artisan command
            'php artisan make:resource ProductCollection'
            Please note that there are 2 types of reources, one is ResourceCollection and the 
            other is simply Resource. Here we are creating ResourceCollection
            For detail information refer to https://laravel.com/docs/5.7/eloquent-resources
*/

class ProductCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return parent::toArray($request);
    }
}
